CREATE TABLE Country
(
 CountryId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 Name VARCHAR(255) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);
  
CREATE TABLE State
(
 StateId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 CountryId INT NOT NULL,
 Name VARCHAR(255) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE City
(
 CityId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 StateId INT NOT NULL,
 Name VARCHAR(255) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);
 
CREATE TABLE Address
(
 AddressId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 BuildingNumber INT NOT NULL,
 CityId INT NOT NULL,
 StreetName VARCHAR(255) NOT NULL,
 Locality VARCHAR(255) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE User
(
  Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  MobileNumber VARCHAR(15) NOT NULL,
   CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

 
CREATE TABLE Student
(
StudentId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
UserId INT NOT NULL,
CollegeId INT NOT NULL,
DepartmentId INT NOT NULL,
Resume VARCHAR(255) NOT NULL
);

CREATE TABLE PlacementOfficer
(
 PlacementOffId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 UserId INT NOT NULL,
 CollegeId INT NOT NULL,
 JobId INT NOT NULL
);

CREATE TABLE College
(
CollegeId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
InstituteId INT NOT NULL,
AddressId INT NOT NULL,
CollegeName VARCHAR(255) NOT NULL,
Email VARCHAR(100) UNIQUE NOT NULL,
PhoneNumber VARCHAR(15) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE InstituteType

(
  InstituteId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  InstituteType VARCHAR(255) NOT NULL,
  CreatedDate DATE DEFAULT GETDATE(),
  ModifiedDate DATE  GETDATE()
)
 
 
CREATE TABLE Company
(
  CompanyId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  AddressId INT NOT NULL,
  CompanytypeId INT NOT NULL,
  CompanyName VARCHAR(50) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  CreatedDate DATE DEFAULT GETDATE(),
  ModifiedDate DATE  GETDATE()
);

 CREATE TABLE Companytype
(
 CompanytypeId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 Type VARCHAR(50) NOT NULL,
  CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
); 

CREATE TABLE Jobpost
(
  JobId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  CompanyId INT NOT NULL,
  SkillId INT NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Description  VARCHAR(255) NOT NULL,
  JobLocation VARCHAR(255) NOT NULL,
  CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE Application
(
AppliacationId  INT IDENTITY(1,1) PRIMARY KEY  NOT NULL,
StudentId INT  NOT NULL,
JobId INT  NOT NULL,
StatusId INT  NOT NULL,
PlacementOffId INT NOT NULL,
DateApllied DATE NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE Department
(
  DepartmentId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Name VARCHAR(255) NOT NULL,
   CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);

CREATE TABLE Skills
(
 SkillId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
 SkillName VARCHAR(255) NOT NULL,
  CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
);
 
 CREATE TABLE ApplicationStatus
(
  StatusId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  Status VARCHAR(255) NOT NULL,
 CreatedDate DATE DEFAULT GETDATE(),
 ModifiedDate DATE  GETDATE()
)
